<?php
/**
 * @file
 * block_region_injector
 * block_region_injector.module
 *
 * Created by Jake Wise 03/06/2016.
 *
 * You are permitted to use, modify, and distribute this file in accordance with
 * the terms of the license agreement accompanying it.
 */

/**
 * Implements hook_preprocess().
 */
function block_region_injector_preprocess(&$variables, $hook) {
  if ($hook !== 'page' && !isset($variables['blocks'])) {
    $variables['blocks'] = \Drupal::service('block.page_display_manager')->getBlockViewsByRegion();
  }
}
